version: 0.1

phases:
  install:
    commands:
    - apt-get update
    - apt-get install software-properties-common python-software-properties -y
    - add-apt-repository ppa:webupd8team/java -y
    - add-apt-repository ppa:cwchien/gradle -y
    - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    - apt-get update
    - apt-get install oracle-java8-installer oracle-java8-set-default -y
    - apt-get install gradle -y
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install docker-compose
    - pip install awscli

  build:
    commands:
    - gradle dockerCompose
    - gradle clean test itest -Penv=test --stacktrace
    - gradle dockerComposeDown
    - gradle clean build publishToECR -Penv=prod -x test --stacktrace
